### ISSUE TITLE
Regarding Evaluation metric

### ISSUE THREAD

**Issue by awdrkjlk966** [BarqueroGerman/FlowMDM#1]
Thank you for your amazing work!

I have a few questions regarding the evaluation metrics used for the transition part, specifically with the HumanML3D dataset. Given that there's no ground truth available, could you please explain how the FID, Div, PJ, AUJ was calculated for this dataset?

Furthermore, concerning the Peak Jerk metric, I'm interested in knowing the values used for the HumanML3D dataset.
Could you please share the details of Jerk calculation? I'm wondering what values are used among 263 dimension. did the calculation of jerk consider only the joint locations, or did it also include joint rotations?  Additionally, is the delta_t for Jerk calculation defined by frame or second?

I appreciate your time and look forward to your insights.

Best,
awdrkjlk966

**Comment by BarqueroGerman** [comment]
Hi!

We plan to release the part of the code you are interested in next week. For transitions evaluation, we follow the evaluation pipeline from PriorMDM ([paper](https://arxiv.org/pdf/2303.01418.pdf)), where transitions are only evaluated for text-agnostic metrics. For this, the GT motions consist of segments randomly sampled from the dataset with length = transition length.

All jerk-related computations were applied to the body joints after applying forward kinematics. delta_t is defined by frame. The average values will be shared with the code next week.

Thanks for your interest in our work!
