### ISSUE TITLE
How to use trajectory to guide the motion generation?

### ISSUE THREAD

**Issue by JingyunLiang** [BarqueroGerman/FlowMDM#16]
How to use trajectory to guide the motion generation? For example, how to generate motions with the given trajectory like in Figure 1-Right of the paper?

**Comment by BarqueroGerman** [comment]
Hi Jingyun,

By default, the project does not support such trajectory control. However, I did the plot by leveraging the logic implemented in:
https://github.com/BarqueroGerman/FlowMDM/blob/e81c67fa02c5284b4b32a757c575c9b9fcaaa82a/diffusion/gaussian_diffusion.py#L307

You can first build your trajectory in the representation of the dataset: x-y offsets for HumanML3D or in global positions for Babel. Then you can set it to the inpainted motion and the inpainting mask variables in model_kwargs, which the code above will use to build the output of each denoising step, thus harmonizing the generation with the inpainted trajectory. This implementation is inherited from MDM.
