### ISSUE TITLE
Is it possible to train FlowMDM with a custom dataset ?

### ISSUE THREAD

**Issue by senecobis** [BarqueroGerman/FlowMDM#17]
Hi, looking at the training and in particular at `def run_loop(self):` two quantities should be provided:
1st motion and 2nd cond which consists of ['mask', 'lengths', 'text', 'all_texts', 'all_lengths', 'conditions_mask', 'pe_bias', 'pos_pe_abs', 'text_embeddings'].

My doubt are why motion is 64 x 135 x 201 ? I guess 64 is the batch by why the rest it 135 x 201 ? How a standard 3D pose estimation of size N_frames x N_joints x 3 can be mapped to that ?

Also based on what 'mask' values are decided ?

**Comment by BarqueroGerman** [comment]
Hi!

Yes, it is possible. You need to build a custom data loader for your dataset. You are free to use any representation you'd like. The features I used for Babel are 135 --> 3 for XYZ position and 132 for the 22 6D rotations (1 for global orientation, 21 for bone rotations, i.e., SMPL pose parameters).

If you build a custom data loader like the one for Babel or HumanML3D, you shouldn't worry about the logic of the mask creation. The mask is used in the APE stage of the denoising.

German
