### ISSUE TITLE
An error occurs when running environment.yml。What should I do?

### ISSUE THREAD

**Issue by qfb594** [BarqueroGerman/FlowMDM#7]
PackagesNotFoundError: The following packages are not available from current channels:

  - zlib==1.2.13=h5eee18b_0
  - xz==5.2.6=h5eee18b_0
  - tk==8.6.12=h1ccaba5_0
  - sqlite==3.40.0=h5082296_0
  - setuptools==65.5.0=py38h06a4308_0
  - readline==8.2=h5eee18b_0
  - python==3.8.15=h7a1cb2a_2
  - pip==22.2.2=py38h06a4308_0
  - openssl==1.1.1s=h7f8727e_0
  - numpy-base==1.23.4=py38h31eccc5_0
  - numpy==1.23.4=py38h14f4228_0
  - ncurses==6.3=h5eee18b_3
  - mkl_random==1.2.2=py38h51133e4_0
  - mkl_fft==1.3.1=py38hd3c417c_0
  - mkl-service==2.4.0=py38h7f8727e_0
  - mkl==2021.4.0=h06a4308_640
  - libstdcxx-ng==11.2.0=h1234567_1
  - libgomp==11.2.0=h1234567_1
  - libgcc-ng==11.2.0=h1234567_1
  - libffi==3.4.2=h6a678d5_6
  - ld_impl_linux-64==2.38=h1181459_1
  - intel-openmp==2021.4.0=h06a4308_3561
  - certifi==2022.9.24=py38h06a4308_0
  - ca-certificates==2022.10.11=h06a4308_0
  - _openmp_mutex==5.1=1_gnu

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://conda.anaconda.org/conda-forge/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by BarqueroGerman** [comment]
Hi!

Which version of conda are you using?
Could you try to run:

`conda config --env --add channels conda-forge
`

and try to install the environment again, please?

**Comment by qfb594** [comment]
![QQ浏览器截图20240422161832](https://github.com/BarqueroGerman/FlowMDM/assets/48076384/67bb0626-eaf6-46f8-9e24-3b8ab2ec531e)

**Comment by BarqueroGerman** [comment]
I can't replicate your error... Did you manage to fix this? If so, could you share the solution? Thanks!

**Comment by BarqueroGerman** [comment]
Closing it since nobody else complained about this...
