### ISSUE TITLE
An error(maybe) motion occured when I use a modified input.

### ISSUE THREAD

**Issue by Heibaiii** [BarqueroGerman/FlowMDM#9]
When I modified the sequences in the file "composition_babel.json", I have gotten a strange result.
This is my modification:
     line 43-48:
                "kung fu pose"--->"kung fu pose",
		"kung fu pose"--->"dance",
		"kung fu pose"--->"lie down",
		"step left"---> "stand up",
		"throw baseball"--->"throw baseball",
		"catch the ball"--->"catch the ball"

The result is here, may I ask if this is normal？
https://github.com/BarqueroGerman/FlowMDM/assets/72643015/97122869-7fe9-4c2c-a592-998b7b013553

**Comment by BarqueroGerman** [comment]
Hi!

Thanks for your interest in our work! Changing the sequence of texts will definitely affect the quality of the generation. Lying down is one of the actions that is less represented in the dataset and might cause some weird motions like the one you show when transitioning from and to other actions.
